# Generated by Django 3.2.9 on 2021-12-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20211210_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('setup', models.CharField(max_length=1)),
            ],
        ),
    ]
