# Generated by Django 3.2.9 on 2021-12-13 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20211212_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checked',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='pedal',
            name='guitars',
            field=models.ManyToManyField(to='main_app.Guitar'),
        ),
        migrations.AlterField(
            model_name='checked',
            name='date',
            field=models.DateField(verbose_name='checked date'),
        ),
    ]
